# Which hosts are actually in the OpTC eCAR bundles, and how many records each.
#
# ASCII ONLY IN THIS FILE.
#
# WHY THIS EXISTS
#
# The eCAR bundles are named by SysClient number range (AIA-301-325), so for a
# SysClient host you can tell which bundle to open by arithmetic. DC1 is not a
# SysClient. It is a domain controller and the naming carries no information
# about it, so "is DC1's endpoint telemetry in what we downloaded" cannot be
# answered from the file names.
#
# It has to be answered before E1 is designed. The Day 1 pivot chain ends with
# lsadump on DC1 (analysis/optc/), and if DC1 has no eCAR then that last step is
# invisible to any endpoint detector - which changes what E1-b is allowed to
# claim, not just how well it scores. See docs/09-optc-acquisition.md.
#
# HOW
#
# Every record is one JSON object on one line with a "hostname" field. We do not
# parse JSON: a byte scan for the literal `"hostname":"` and a read to the next
# quote is an order of magnitude faster, and 380 GB of decompressed text is
# enough that the difference is hours. Same reason Measure-AuthJoin.ps1 compiles
# a scanner instead of using Select-String.
#
# Usage:
#   .\scripts\Measure-OptcHosts.ps1
#   .\scripts\Measure-OptcHosts.ps1 -Root F:\mc-cycop-data\raw\optc -OutJson analysis\optc\host-index.json
#
# Output: one row per (bundle, hostname) with a record count, plus a summary of
# which bundle each host lives in.

param(
  [string]$Root    = 'F:\mc-cycop-data\raw\optc',
  [string]$OutJson = "$PSScriptRoot\..\analysis\optc\host-index.json",
  [string]$Filter  = 'ecar',
  [switch]$Quick
)

$ErrorActionPreference = 'Stop'

$cs = @'
using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Text;

public class OptcHostScan
{
    public long Lines;
    public long Bytes;
    public long Hits;
    public Dictionary<string, long> Hosts = new Dictionary<string, long>();

    // The pattern is "hostname":" - 12 bytes. Records are machine generated by
    // one producer, so the spacing is stable; if a future release adds a space
    // after the colon this finds nothing and the count of zero says so loudly
    // rather than reporting a wrong answer quietly.
    static readonly byte[] Pat = Encoding.ASCII.GetBytes("\"hostname\":\"");

    public void Run(string path, long maxBytes)
    {
        using (FileStream fs = File.OpenRead(path))
        using (GZipStream gz = new GZipStream(fs, CompressionMode.Decompress))
        {
            const int BUF = 4 * 1024 * 1024;
            const int TAIL = 256;              // longest thing we might straddle
            byte[] buf = new byte[BUF + TAIL];
            int carry = 0;

            while (true)
            {
                int got = gz.Read(buf, carry, BUF);
                if (got <= 0) break;
                int end = carry + got;
                Bytes += got;

                int i = 0;
                int lastSafe = end - TAIL;
                if (lastSafe < 0) lastSafe = 0;

                while (i < end)
                {
                    if (buf[i] == (byte)'\n') { Lines++; i++; continue; }
                    if (buf[i] != Pat[0]) { i++; continue; }
                    if (i + Pat.Length >= end) break;

                    bool ok = true;
                    for (int k = 1; k < Pat.Length; k++)
                    {
                        if (buf[i + k] != Pat[k]) { ok = false; break; }
                    }
                    if (!ok) { i++; continue; }

                    int s = i + Pat.Length;
                    int e = s;
                    while (e < end && buf[e] != (byte)'"' && e - s < 200) e++;
                    if (e >= end) break;

                    string host = Encoding.ASCII.GetString(buf, s, e - s);
                    long n;
                    if (Hosts.TryGetValue(host, out n)) Hosts[host] = n + 1;
                    else Hosts[host] = 1;
                    Hits++;
                    i = e + 1;
                }

                // keep the unconsumed tail so a pattern split across two reads
                // is still found
                carry = end - i;
                if (carry > TAIL) carry = TAIL;
                if (carry > 0) Buffer.BlockCopy(buf, end - carry, buf, 0, carry);

                if (maxBytes > 0 && Bytes >= maxBytes) break;
            }
        }
    }
}
'@

Add-Type -TypeDefinition $cs -Language CSharp

$files = @(Get-ChildItem -LiteralPath $Root -Recurse -File -Filter *.gz |
           Where-Object { $_.FullName -like ('*' + $Filter + '*') } |
           Sort-Object Length)

if ($files.Count -eq 0) { throw ("no *.gz matching '$Filter' under $Root") }

$cap = 0
if ($Quick) { $cap = 512MB }

Write-Host ''
Write-Host ('optc host index   files={0}   filter={1}{2}' -f $files.Count, $Filter, $(if ($Quick) { '   QUICK (512 MB/file)' } else { '' }))
Write-Host ('-' * 78)

$rows = New-Object System.Collections.ArrayList
$all  = @{}
$swAll = [System.Diagnostics.Stopwatch]::StartNew()
$idx = 0

foreach ($f in $files) {
    $idx++
    $rel = $f.FullName.Substring($Root.Length).TrimStart('\', '/')
    $scan = New-Object OptcHostScan
    $sw = [System.Diagnostics.Stopwatch]::StartNew()
    try {
        $scan.Run($f.FullName, $cap)
    } catch {
        Write-Host ('  [{0}/{1}] {2}  SCAN FAILED: {3}' -f $idx, $files.Count, $rel, $_.Exception.Message)
        continue
    }
    $sw.Stop()

    $hostList = @($scan.Hosts.Keys | Sort-Object)
    foreach ($h in $hostList) {
        [void]$rows.Add([ordered]@{ bundle = $rel; host = $h; records = [long]$scan.Hosts[$h] })
        if ($all.ContainsKey($h)) { $all[$h] = [long]$all[$h] + [long]$scan.Hosts[$h] }
        else { $all[$h] = [long]$scan.Hosts[$h] }
    }

    # Anything that is not SysClientNNNN is the interesting part. That is the
    # whole reason this script exists, so it gets called out per file.
    $odd = @($hostList | Where-Object { $_ -notmatch '^SysClient\d+' })
    $oddTxt = ''
    if ($odd.Count -gt 0) { $oddTxt = '   ** ' + ($odd -join ', ') }

    Write-Host ('  [{0,3}/{1}] {2,-58} {3,6:N1} GB  {4,3} host(s)  {5,5:N0}s{6}' -f `
                $idx, $files.Count, $rel, ($scan.Bytes / 1GB), $hostList.Count, $sw.Elapsed.TotalSeconds, $oddTxt)
}

$swAll.Stop()

$hosts = @($all.Keys | Sort-Object)
$sys   = @($hosts | Where-Object { $_ -match '^SysClient\d+' })
$other = @($hosts | Where-Object { $_ -notmatch '^SysClient\d+' })

Write-Host ''
Write-Host '=== summary ==='
Write-Host ('  distinct hosts     : {0}' -f $hosts.Count)
Write-Host ('  SysClient hosts    : {0}' -f $sys.Count)
Write-Host ('  non-SysClient      : {0}' -f $other.Count)
foreach ($h in $other) {
    $where = @($rows | Where-Object { $_.host -eq $h } | ForEach-Object { $_.bundle })
    Write-Host ('    {0,-32} {1,12:N0} records   in {2}' -f $h, $all[$h], ($where -join ', '))
}
Write-Host ('  elapsed            : {0:N0} s' -f $swAll.Elapsed.TotalSeconds)
Write-Host ''

$dc = @($other | Where-Object { $_ -match '(?i)^dc\d' })
if ($dc.Count -gt 0) {
    Write-Host ('ANSWER: DC eCAR present -> {0}' -f ($dc -join ', '))
} else {
    Write-Host 'ANSWER: no DC* host appears in any scanned eCAR bundle.'
    Write-Host '        E1-b cannot claim endpoint observation of the DC1 lsadump step.'
}
Write-Host ''

$dir = Split-Path $OutJson -Parent
if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Force $dir | Out-Null }
$report = [ordered]@{
    generated     = (Get-Date).ToString('o')
    generator     = 'scripts/Measure-OptcHosts.ps1'
    root          = $Root
    filter        = $Filter
    quick         = [bool]$Quick
    files_scanned = $files.Count
    elapsed_sec   = [math]::Round($swAll.Elapsed.TotalSeconds, 1)
    distinct_hosts = $hosts.Count
    sysclient_hosts = $sys.Count
    non_sysclient   = $other
    dc_present      = ($dc.Count -gt 0)
    host_totals     = ($all.GetEnumerator() | Sort-Object Name | ForEach-Object { [ordered]@{ host = $_.Key; records = $_.Value } })
    per_bundle      = @($rows)
}
[IO.File]::WriteAllText($OutJson, ($report | ConvertTo-Json -Depth 6), (New-Object Text.UTF8Encoding($false)))
Write-Host ("report: {0}" -f $OutJson)
Write-Host ''
